export const inputs = [
   {
      id: 1,
      name: "name",
      type: "text",
      placeholder: "Name",
      errorMessage:
      "Name should be 3-16 characters and shouldn't include any special character!",
      label: "Name",
      pattern: "^[A-Za-z0-9]{3,16}$",
      required: true,
   },
   {
      id: 2,
      name: "organisationNr",
      type: "text",
      placeholder: "Organisation Nummer",
      errorMessage: "The field is required",
      label: "Organisation Nummer",
      required: true,
   },
   {
      id: 3,
      name: "vatNr",
      type: "text",
      placeholder: "VAT Nummer",
      errorMessage: "Wrong format! You need to write SExxxxxxxxxx.",
      label: "VAT Nummer",
      pattern: "^SE[0-9]{10}$",
      required: true,
   },
   
   {
      id: 4,
      name: "reference",
      type: "text",
      placeholder: "Reference",
      errorMessage: "The field is required",
      label: "Reference",
      required: true,
   },
   {
      id: 5,
      name: "paymentTerm",
      type: "number",
      placeholder: "Payment Term",
      errorMessage: "The field is required",
      label: "Payment Term",
      required: true,
   },
   {
      id: 6,
      name: "website",
      type: "text",
      placeholder: "Website",
      errorMessage: "The field is required",
      label: "Website",
      required: true,
   },
   {
      id: 7,
      name: "email",
      type: "email",
      placeholder: "Email",
      errorMessage: "It should be a valid email address!",
      label: "Email",
      required: true,
   },
   {
      id: 8,
      name: "phoneNumber",
      type: "text",
      placeholder: "Phone Number",
      errorMessage: "The field is required",
      label: "Phone Number",
      required: true,
   },

];